### ISSUE TITLE
Unable to save settings

### ISSUE THREAD

**Issue by heiyutian** [raingart/New-Horizons-for-YouTube-extension#1]
1.Unable to save settings
2.Channel page The number of display video, I picture marked.
https://ftp.bmp.ovh/imgs/2020/01/30c1e6f7c0602a48.png

**Comment by raingart** [comment]
>1.Unable to save settings
And what specific settings does not save? All? Are there any errors in the browser console?

>2.Channel page The number of display video, I picture marked.
And what incorrectly displays? Count of videos?
I could not find the channel on youtube many respected "Fire Tree". What when check video number of videos. Only this [link](https://m.weibo.cn/p/index?containerid=1008082ff058c72814a6005ec4ff1b40053f79&extparam=%E4%B8%89%E5%9B%BD%E6%9D%80%E7%81%AB%E6%A0%91&luicode=10000011&lfid=231522type%3D1%26t%3D10%26q%3D%23%E5%AF%86%E5%AE%A4%E5%A4%A7%E9%80%83%E8%84%B1%E5%A4%A7%E7%A5%9E%E7%89%88%23&featurecode=10000001)

Can you try to describe what does not work and on which page/channel?

**Comment by heiyutian** [comment]
I mean
1. After the extension was updated a few days ago, I can't modify and save the settings
2.I want to increase functionality, Able to display the number of videos on the channel page

**Comment by heiyutian** [comment]
I test that I intend to turn off this button. After clicking save, it does not take effect. I answer this page again, and the button is still displayed

https://ftp.bmp.ovh/imgs/2020/01/89a4a100548bcc3e.png

**Comment by raingart** [comment]
An interesting glitch. You can show the output in the browser console for the extension options page.
So that I can figure out what is the reason bug.

If you do not want to bother then try reinstalling the extension. I am sure that eo will solve the problem.

**Comment by raingart** [comment]
I added a video how to save the output from the console. If you do not know how to do it

https://drive.google.com/open?id=1GRkYCs_McHhQlxNLBiZfviyuCwNI6WX3

**Comment by heiyutian** [comment]
I uninstalled and reinstalled it. I can change the settings at will. No problem

**Comment by raingart** [comment]
Perfectly. If you have questions or problems, please contact.
And try to look at the console. Often there it is indicated what is the cause of the error.
Good luck!
