### ISSUE TITLE
[ERROR PLUGIN] Normalize video title

### ISSUE THREAD

**Issue by Black-Sunlight** [raingart/New-Horizons-for-YouTube-extension#2]
VM839:40 [ERROR PLUGIN] Normalize video title
SyntaxError: Invalid regular expression: /([A-ZÃ€-Ã–Ã˜-ÃžÄ€Ä‚Ä„Ä†ÄˆÄŠÄŒÄŽÄÄ’Ä”Ä–Ä˜ÄšÄœÄžÄ Ä¢Ä¤Ä¦Ä¨ÄªÄ¬Ä®Ä°Ä²Ä´Ä¶Ä¹Ä»Ä½Ä¿ÅÅƒÅ…Å‡ÅŠÅŒÅŽÅÅ’Å”Å–Å˜ÅšÅœÅžÅ Å¢Å¤Å¦Å¨ÅªÅ¬Å®Å°Å²Å´Å¶Å¸-Å¹Å»Å½Æ-Æ‚Æ„Æ†-Æ‡Æ‰-Æ‹ÆŽ-Æ‘Æ“-Æ”Æ–-Æ˜Æœ-ÆÆŸ-Æ Æ¢Æ¤Æ¦-Æ§Æ©Æ¬Æ®-Æ¯Æ±-Æ³ÆµÆ·-Æ¸Æ¼Ç„Ç‡ÇŠÇÇÇ‘Ç“Ç•Ç—Ç™Ç›ÇžÇ Ç¢Ç¤Ç¦Ç¨ÇªÇ¬Ç®Ç±Ç´Ç¶-Ç¸ÇºÇ¼Ç¾È€È‚È„È†ÈˆÈŠÈŒÈŽÈÈ’È”È–È˜ÈšÈœÈžÈ È¢È¤È¦È¨ÈªÈ¬È®È°È²Èº-È»È½-È¾ÉÉƒ-É†ÉˆÉŠÉŒÉŽÍ°Í²Í¶Î†Îˆ-ÎŠÎŒÎŽ-ÎÎ‘-Î¡Î£-Î«ÏÏ’-Ï”Ï˜ÏšÏœÏžÏ Ï¢Ï¤Ï¦Ï¨ÏªÏ¬Ï®Ï´Ï·Ï¹-ÏºÏ½-Ð¯Ñ Ñ¢Ñ¤Ñ¦Ñ¨ÑªÑ¬Ñ®Ñ°Ñ²Ñ´Ñ¶Ñ¸ÑºÑ¼Ñ¾Ò€ÒŠÒŒÒŽÒÒ’Ò”Ò–Ò˜ÒšÒœÒžÒ Ò¢Ò¤Ò¦Ò¨ÒªÒ¬Ò®Ò°Ò²Ò´Ò¶Ò¸ÒºÒ¼Ò¾Ó€-ÓÓƒÓ…Ó‡Ó‰Ó‹ÓÓÓ’Ó”Ó–Ó˜ÓšÓœÓžÓ Ó¢Ó¤Ó¦Ó¨ÓªÓ¬Ó®Ó°Ó²Ó´Ó¶Ó¸ÓºÓ¼Ó¾Ô€Ô‚Ô„Ô†ÔˆÔŠÔŒÔŽÔÔ’Ô”Ô–Ô˜ÔšÔœÔžÔ Ô¢Ô±-Õ–á‚ -áƒ…á¸€á¸‚á¸„á¸†á¸ˆá¸Šá¸Œá¸Žá¸á¸’á¸”á¸–á¸˜á¸šá¸œá¸žá¸ á¸¢á¸¤á¸¦á¸¨á¸ªá¸¬á¸®á¸°á¸²á¸´á¸¶á¸¸á¸ºá¸¼á¸¾á¹€á¹‚á¹„á¹†á¹ˆá¹Šá¹Œá¹Žá¹á¹’á¹”á¹–á¹˜á¹šá¹œá¹žá¹ á¹¢á¹¤á¹¦á¹¨á¹ªá¹¬á¹®á¹°á¹²á¹´á¹¶á¹¸á¹ºá¹¼á¹¾áº€áº‚áº„áº†áºˆáºŠáºŒáºŽáºáº’áº”áºžáº áº¢áº¤áº¦áº¨áºªáº¬áº®áº°áº²áº´áº¶áº¸áººáº¼áº¾á»€á»‚á»„á»†á»ˆá»Šá»Œá»Žá»á»’á»”á»–á»˜á»šá»œá»žá» á»¢á»¤á»¦á»¨á»ªá»¬á»®á»°á»²á»´á»¶á»¸á»ºá»¼á»¾á¼ˆ-á¼á¼˜-á¼á¼¨-á¼¯á¼¸-á¼¿á½ˆ-á½á½™á½›á½á½Ÿá½¨-á½¯á¾¸-á¾»á¿ˆ-á¿‹á¿˜-á¿›á¿¨-á¿¬á¿¸-á¿»â„‚â„‡â„‹-â„â„-â„’â„•â„™-â„â„¤â„¦â„¨â„ª-â„â„°-â„³â„¾-â„¿â……â†ƒâ°€-â°®â± â±¢-â±¤â±§â±©â±«â±-â±¯â±²â±µâ²€â²‚â²„â²†â²ˆâ²Šâ²Œâ²Žâ²â²’â²”â²–â²˜â²šâ²œâ²žâ² â²¢â²¤â²¦â²¨â²ªâ²¬â²®â²°â²²â²´â²¶â²¸â²ºâ²¼â²¾â³€â³‚â³„â³†â³ˆâ³Šâ³Œâ³Žâ³â³’â³”â³–â³˜â³šâ³œâ³žâ³ â³¢ê™€ê™‚ê™„ê™†ê™ˆê™Šê™Œê™Žê™ê™’ê™”ê™–ê™˜ê™šê™œê™žê™¢ê™¤ê™¦ê™¨ê™ªê™¬êš€êš‚êš„êš†êšˆêšŠêšŒêšŽêšêš’êš”êš–êœ¢êœ¤êœ¦êœ¨êœªêœ¬êœ®êœ²êœ´êœ¶êœ¸êœºêœ¼êœ¾ê€ê‚ê„ê†êˆêŠêŒêŽêê’ê”ê–ê˜êšêœêžê ê¢ê¤ê¦ê¨êªê¬ê®ê¹ê»ê½-ê¾êž€êž‚êž„êž†êž‹ï¼¡-ï¼º]|\ud801[\udc00-\udc27]|\ud835[\udc00-\udc19\udc34-\udc4d\udc68-\udc81\udc9c\udc9e-\udc9f\udca2\udca5-\udca6\udca9-\udcac\udcae-\udcb5\udcd0-\udce9\udd04-\udd05\udd07-\udd0a\udd0d-\udd14\udd16-\udd1c\udd38-\udd39\udd3b-\udd3e\udd40-\udd44\udd46\udd4a-\udd50\udd6c-\udd85\udda0-\uddb9\uddd4-\udded\ude08-\ude21\ude3c-\ude55\ude70-\ude89\udea8-\udec0\udee2-\udefa\udf1c-\udf34\udf56-\udf6e\udf90-\udfa8\udfca]){2,}/: Range out of order in character class
    at Object._runtime (chrome-extension://miiheelkbegpkflplpmmkidaklfgjecb/plugins/other/normalize-video-title.js:16:34)
    at _plugins_executor (<anonymous>:32:23)
    at processLander (<anonymous>:88:13)
    at <anonymous>:65:13

**Comment by raingart** [comment]
what browser and version are you using?

**Comment by Black-Sunlight** [comment]
Yandex | 86.0.4240.81 (64-разрядная версия)
ОС | Windows 10 OS Version 2009 (Build 19042.630)
JavaScript | V8 8.6.395.17
Flash | (отключено)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.114 YaBrowser/20.11.1.81 Yowser/2.5 Safari/537.36

**Comment by raingart** [comment]
I did not find ver. 20.11.1.81.
checked on ver. 20.11.0.821 there is no error. 
I'll try to change the variable declarations of the regular expression. In the updated extension.

**Comment by raingart** [comment]
I cannot go through the _Developer Program Policies_ to update an extension.
Probably the **current version** of the extension will remain the **latest**.

**Comment by Black-Sunlight** [comment]
:( 
I turned off Normalize option and now no error appears, maybe it's in my cache, thank you anyway to fastests react i have ever seen, hope that error no one else will appears  :)

**Comment by raingart** [comment]
@Black-Sunlight good luck!
