### ISSUE TITLE
Extension is gone from Chrome Webstore

### ISSUE THREAD

**Issue by alkaris2** [raingart/New-Horizons-for-YouTube-extension#3]
The browser extension is no longer up and available on the Chrome Webstore, what happened?

**Comment by raingart** [comment]
There are problems with initializing plugins. I do not like that the core of plugins is the function of waiting and monitoring the appearance of html elements, with the necessary attr.
**I decided to remove from the store until I rewrite.**
I tried to replace it with internal events (yt-action) to minimize the load on page load. But the initiative failed. After that I took a break and felt lazy. 
Also, one of the users wrote that the reason for the deletion was the restart of the video when the quality was changed.

And updated item _Developer Program Policies_ prevents with the update. I need to wait from 3 to 7 days for the expansion to pass the moderation. Up to this point I can already want to release a new version.
for this I like the service much more:
https://greasyfork.org/en/scripts/by-site/youtube.com?sort=updated
but the mistake was that I wanted each plugin to be a separate isolated file. This creates more problems than it solves.

If you want you can use the old version or choose another similar extension from the thousands available
The closest in functionality: [#1](https://chrome.google.com/webstore/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle), [#2](https://chrome.google.com/webstore/detail/improve-youtube-open-sour/bnomihfieiccainjcjblhegjgglakjdd)
also i love this extension: [#3](https://chrome.google.com/webstore/detail/tweaks-for-youtube/ogkoifddpkoabehfemkolflcjhklmkge)
And protic all that is missing can be found [here](https://greasyfork.org/en/scripts/by-site/youtube.com?sort=updated)

In **general**, the **reason** is that I spent a lot of time on the expansion and it still works like a piece of shit. I'll try to fix it at the end of the year. Then I will publish a new version. But the main reason was that I was able to set up video forwarding directly to the local native MPV player.

**Comment by raingart** [comment]
New ver.1.10.0 prepared
major changes:
- rewritten bootloader
- most plugins have been refracted
